services:
  menu-service-api:
    container_name: menu-service-api
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    tmpfs:
      - /usr/src/app/tmp/pids
      - /usr/src/app/tmp/sockets
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres:15.4-alpine3.18
    ports:
      - 54325:5432
    container_name: postgres
    user: postgres
    command: "postgres -c max_connections=200 -c wal_level=logical"
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
